CREATE TABLE supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_info VARCHAR(255)
);

CREATE TABLE dog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    breed VARCHAR(255),
    badge_id VARCHAR(100),
    kennelling_characteristic VARCHAR(100),
    supplier_id BIGINT,
    gender VARCHAR(20),
    birth_date DATE,
    date_acquired DATE,
    current_status VARCHAR(50),
    leaving_date DATE,
    leaving_reason VARCHAR(50),
    deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_dog_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);
